version: '3.8'

services:
  postgres:
    image: 'postgres:15'
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app
    ports:
      - 5432:5432

  redis:
    image: 'bitnami/redis:6.2'
    networks:
      - app
    ports:
      - 6379:6379

networks:
  app:
    driver: bridge

volumes:
  db:
    driver: local
